FROM resin/%%RESIN_MACHINE_NAME%%-python

# Enable systemd
ENV INITSYSTEM on

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["python","run.py"]
